### PR TITLE
Add Zulip plugin for Errbot.

### PR DESCRIPTION
**Pull request by derAnfaenger**
This is a first basic implementation. It's code is based on the [telegram plugin](https://github.com/errbotio/errbot/blob/master/errbot/backends/telegram_messenger.py). Like the telegram plugin, it supports private messages, group chats and file uploads. Additionally, Most `Room` operations  like `occupants`, `join`, `leave` are available for Zulip streams. `create` and `destroy` currently throw errors, due to API constraints. 

I'm glad for any feedback. The plan for this repo is to be integrated into `https://github.com/errbotio`.

### CODE REVIEW

**Comment by derAnfaenger** [comment]
Update: Added setup instructions to README.md

**Comment by timabbott** [comment]
I skimmed it and didn't see anything broken.  @derAnfaenger have you tested the functionality manually?  I can invite some of the folks who use ErrBot and have a Zulip instance to try this out if it's ready for that; I imagine that's the best way to figure out if it has bugs.

**Comment by derAnfaenger** [comment]
I tested everything except `ZulipRoom.exists()`, `ZulipRoom.joined()` and `prefix_groupchat_reply()`. You can see most of the testing in #bot testing. If you could invite some folks to try this out, that'd be great. I can also test the remaining functions with some adapted plugin.

**Comment by timabbott** [comment]
Great.  @sils would you folks be up for testing this integration out?  It'd be super helpful.

**Comment by sils** [comment]
CC @meetmangukiya - interested?

**Comment by derAnfaenger** [comment]
Merged this for now, so that the repo can be simply cloned for testing.

**Pull request merged**
